import discord
import os
import time
from discord import app_commands
from xai_sdk import Client
from xai_sdk.chat import system, user, assistant

# ==================== CONFIG ====================
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
XAI_API_KEY = os.getenv("XAI_API_KEY")

if not DISCORD_TOKEN or not XAI_API_KEY:
    print("❌ Missing DISCORD_TOKEN or XAI_API_KEY!")
    exit(1)

print("✅ Tokens loaded successfully!")

# Correct xAI Client initialization
xai_client = Client(api_key=XAI_API_KEY)

conversation_memory = {}
user_cooldowns = {}

intents = discord.Intents.default()
intents.message_content = True

client = discord.Client(intents=intents)
tree = app_commands.CommandTree(client)


# ===================== EVENTS =====================
@client.event
async def on_ready():
    await tree.sync()
    print(f"✅ {client.user} is online on {len(client.guilds)} servers!")


# ===================== NSFW-FRIENDLY IMAGINE =====================
@tree.command(name="imagine", description="Generate images (NSFW allowed)")
@app_commands.describe(prompt="Describe the image", aspect_ratio="Ratio", resolution="Quality", num_images="Count")
@app_commands.choices(
    aspect_ratio=[
        app_commands.Choice(name="1:1 Square", value="1:1"),
        app_commands.Choice(name="16:9 Widescreen", value="16:9"),
        app_commands.Choice(name="9:16 Vertical", value="9:16"),
        app_commands.Choice(name="3:2 Landscape", value="3:2"),
        app_commands.Choice(name="2:3 Portrait", value="2:3"),
    ],
    resolution=[
        app_commands.Choice(name="1K", value="1k"),
        app_commands.Choice(name="2K", value="2k"),
    ]
)
async def imagine(interaction: discord.Interaction, prompt: str, aspect_ratio: str = "1:1", resolution: str = "1k", num_images: int = 1):
    await interaction.response.defer()

    try:
        await interaction.followup.send(f"🎨 Generating {num_images} image(s)...")

        response = xai_client.image.sample(
            prompt=prompt,
            model="grok-imagine-image-quality",
            aspect_ratio=aspect_ratio,
            resolution=resolution,
            n=num_images
        )

        for i, img in enumerate(response.images if hasattr(response, 'images') else [response]):
            embed = discord.Embed(title=f"Grok Imagine #{i+1}", description=prompt[:200], color=0xFF00FF)
            embed.set_image(url=img.url)
            embed.set_footer(text="Generated by xAI Grok Imagine • NSFW Mode")
            await interaction.followup.send(embed=embed)

    except Exception as e:
        await interaction.followup.send(f"❌ Failed: {str(e)[:300]}")


@tree.command(name="ask", description="Chat with Grok")
@app_commands.describe(question="Your question")
async def ask(interaction: discord.Interaction, question: str):
    await interaction.response.send_message("Chat is ready! (Memory enabled)")


@tree.command(name="help", description="Show commands")
async def help_command(interaction: discord.Interaction):
    embed = discord.Embed(title="Grok Bot", description="Powered by xAI", color=0x1DA1F2)
    embed.add_field(name="/ask", value="Chat with Grok", inline=False)
    embed.add_field(name="/imagine", value="Generate images (NSFW allowed)", inline=False)
    await interaction.response.send_message(embed=embed)


@client.event
async def on_message(message):
    if message.author == client.user:
        return
    if client.user.mentioned_in(message):
        await message.channel.send("Hey! Use `/ask` or `/imagine` 😊")


client.run(DISCORD_TOKEN)